export const LOGGED_IN = "LOGGED_IN"
export const LOGGED_OUT = "LOGGED_OUT"
export const SIGNUP = "SIGNUP"
export const LOGOUT = "LOGOUT"
export const LOGIN = "LOGIN"

export const FETCH_USERS = "FETCH_USERS"

export const EDIT_PROFILE = "EDIT_PROFILE"
export const FETCH_PROFILE = "FETCH_PROFILE"
export const UPLOAD_PHOTO = "UPLOAD_PHOTO"

export const FETCH_INTERESTS = "FETCH_INTERESTS"

export const FETCH_MATCHES = "FETCH_MATCHES"

export const CREATE_MESSAGE = "CREATE_MESSAGE"
export const FETCH_SENT_MESSAGES = "FETCH_SENT_MESSAGES"
export const FETCH_RECEIVED_MESSAGES = "FETCH_RECEIVED_MESSAGES"

